# Generated by Django 4.0.2 on 2023-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docqueryapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=150000),
        ),
    ]
