# Generated by Django 4.0.2 on 2023-07-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docqueryapi', '0003_watchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcriptId', models.BigAutoField(primary_key=True, serialize=False)),
                ('transcript', models.CharField(max_length=150000)),
                ('transcriptUrl', models.CharField(max_length=150000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
